export default {
  login: '/api/login', // 登录
  logout: '/api/logout', // 退出
  collects: '/api/collects', // 收藏菜单
  userCollectUpdate: '/api/collects/userCollectUpdate', // 更新收藏菜单
  userCollectDel: '/api/collects/userCollectDel', // 取消收藏菜单
  faultAlarm: '/api/faults/fault_alarm', // 获取当前的告警和故障数
  projectOverview: '/api/buildings/projectOverview', // 获取项目概况
  projectDataOverview: '/api/buildings/projectDataOverview', // 获取当前数据概况
  buildingMessage: '/api/buildings/buildingMessage', // 获取仓库信息
  energyDistribution: '/api/gatherSystems/energyDistribution', // 获取能耗分布
  faultsDay: '/api/faults/toDay', // 获取当日告警
  specificEnergyConsumption: '/api/buildings/specificEnergyConsumption', // 获取单位能耗排名
  deviceRunStatus: '/api/buildings/deviceRunStatus', // 获取当前设备运行情况
  alarms: '/api/alarms', // 获取告警数据
  tree: '/api/companies/tree', // 获取树
  userCompanyView: '/api/buildings/userCompanyView', // 获取公司
  floorsPlan: '/api/floors/getPlan', // 获取楼层平面图
  systemsPlan: '/api/airConditionSystems/getPlan', // 获取系统平面图
  temperatureHumidity: '/api/floors/devices/temperatureHumidity', // 获取设备的温湿度
  getcurdata: '/api/gatherSystems/getcurdata', // 获取当前设备数据
  getFloorDevice: '/api/gatherSystems/420661250/getFloorDevice', // 获取楼层设备数据
  pumpCurdata: '/api/pumps/currentRunning', // 获取水泵当前数据
  gethisdata: '/api/gatherSystems/gethisdata', // 获取设备历史数据
  floorOpenCount: '/api/gatherSystems/floorOpenCount', // 获取楼层设备开机数量
  regionsOpenCount: '/api/regions/openCount', // 获取区域设备开机数量
  floorRuntime: '/api/gatherSystems/runTime', // 获取楼层设备运行时长
  regionsRuntime: '/api/regions/runTime', // 获取区域设备运行时长
  devicesRuntime: '/api/controlPanels/runTime', // 获取设备运行时长
  buildingEnergySurvey: '/api/buildings/energySurvey', // 获取仓库的能耗概况
  systemEnergySurvey: '/api/gatherSystems/energySurvey', // 获取系统的能耗概况
  floorElectricity: '/api/floors/electricity', // 获取楼层电能表数据
  deviceElectricity: '/api/gatherSystems/electricity', // 获取设备电能表数据
  electricMeter: '/api/gatherSystems/electricMeter', // 获取电表数据
  energyCompare: '/api/buildings/compare', // 获取仓库能耗对比的数据
  floorEnergy: '/api/buildings/floorEnergy', // 获取仓库各个楼层的数据
  monthEnergy: '/api/buildings/monthEnergy', // 获取仓库今年和去年各个月份的能耗数据
  buildingSurvey: '/api/buildings/survey', // 获取仓库概况
  projectAllocation: '/api/buildings/project_allocation', // 获取仓库区域分布概况
  coolNormal: '/api/buildings/cool_normal', // 获取仓库阴凉和常温库的能耗排名概况
  deviceSurvey: '/api/airConditions/survey', // 获取设备概况
  runtimeEnergy: '/api/gatherSystems/runtime_energy', // 获取设备运行的能耗数据
  series: '/api/series', // 获取产品系列
  products: '/api/products', // 产品相关操作
  synchronous: '/api/products/synchronous', // 产品同步
};
